apiVersion: v1
kind: Pod
metadata:
  name: busybox-worker
  labels:
    app: worker
spec:
  containers:
  - name: busybox
    image: busybox
    # This command creates high CPU usage to ensure Kepler has data to report
    command: ["sh", "-c", "while true; do yes > /dev/null; sleep 0.1; done"]
  restartPolicy: Always